### ISSUE TITLE
[Bug] Permanent Loading

### ISSUE THREAD

**Issue by 99TheDark** [eliasmurcray/ka-notifications#12] opened 2023-03-31 07:20 UTC
I've noticed for the past few days, the notifications never load. Just keep on loading in forever. This may be tied to another separate issue I've had on Khan Academy in which I cannot see replies to comments, just that there are some. Are there any files that would be useful to see?

**Comment by Reginald-Gillespie** [comment] 2023-03-31 12:28
@99TheDark about not being able to see replies on KA, remove the expand key url param from the link and it should load fine.

**Comment by 99TheDark** [comment] 2023-03-31 14:45
I thought it might've been an install issue, so before I posted this I removed and redownloaded the extension 

WKoA thanks! This doesn't work sometimes, but I appreciate it :)

**Comment by 99TheDark** [comment] 2023-03-31 17:42
And now it's working again. Both these glitches happen to go in and out at the same time. They are probably related. Maybe KA API update?

**Comment by Reginald-Gillespie** [comment] 2023-03-31 17:44
Chrome automatically updates extensions, I'd bet that was it. You can see the version in `chrome://extensions` by clicking on details of the extension.

**Comment by 99TheDark** [comment] 2023-03-31 18:15
I doubt it, it hadn't been working even hours after reinstallation

**Comment by eliasmurcray** [comment] 2023-03-31 19:52
I will leave this open for now. We are working on implementing a new feature, once that is squared away I can take a look at the logic once more.

**Comment by 99TheDark** [comment] 2023-03-31 21:07
Sure. I will let you know if it happens again.

**Comment by Reginald-Gillespie** [comment] 2023-04-01 00:04
<img width="688" alt="image" src="https://user-images.githubusercontent.com/109245101/229254653-7535992b-5bd7-4d2b-96e9-af6b895c1820.png">
@eliasmurcray

**Comment by eliasmurcray** [comment] 2023-04-01 06:28
I will need to update that. Truth be told, I have forgotten what that line of code actually does...

**Comment by Reginald-Gillespie** [comment] 2023-04-01 12:28
Always good.
Oh, that makes sense, if it was a help request that he got a reply or answer on and then it went below the top 10 and started working again.

**Comment by 99TheDark** [comment] 2023-04-04 14:33
Well, it hasn't glitched out since. On another issue, every time I get a message, it says I have 10 rather than 1. Weird.

**Comment by Reginald-Gillespie** [comment] 2023-04-04 14:46
Yeah, Issue #17. It's counting all notifications as unread even if only one is

**Comment by eliasmurcray** [comment] 2023-04-05 08:00
It seems that this error may have been caused by an edge case in the string parsing method I used. The new change has been uploaded to the Chrome Web Store and awaiting verification. I will leave this open now and for a week after in case there are other cases to be found.

**Comment by eliasmurcray** [comment] 2023-04-08 23:03
I was going to give it a full week, but it seems to be completely resolved with the new heartbeat script.

**Closed by eliasmurcray** 2023-04-08 23:03 UTC
Labels: bug

**Comment by 99TheDark** [comment] 2023-04-09 06:26
Yes, haven't seen any issues for at least a week.
